# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


artifact_uri: /geotunes/tune-tasks/geotune-qokd9fqyuhxbgyyiuurpxu/201622622176987258/03e8ad57d953415f8c29f473e32e5e0a/artifacts
end_time: 1758705849103
entry_point_name: ''
experiment_id: '201622622176987258'
lifecycle_stage: active
run_id: 03e8ad57d953415f8c29f473e32e5e0a
run_name: geotune-qokd9fqyuhxbgyyiuurpxu_3
source_name: ''
source_type: 4
source_version: ''
start_time: 1758705180795
status: 3
tags: []
user_id: '1001810000'
