# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


artifact_uri: /geotunes/tune-tasks/geotune-qokd9fqyuhxbgyyiuurpxu/201622622176987258/722793af47d143e6967dbb69d812d42b/artifacts
end_time: 1758705173931
entry_point_name: ''
experiment_id: '201622622176987258'
lifecycle_stage: active
run_id: 722793af47d143e6967dbb69d812d42b
run_name: geotune-qokd9fqyuhxbgyyiuurpxu_2
source_name: ''
source_type: 4
source_version: ''
start_time: 1758704529002
status: 3
tags: []
user_id: '1001810000'
