# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


artifact_uri: /geotunes/tune-tasks/geotune-qokd9fqyuhxbgyyiuurpxu/201622622176987258/c0ce679ccfb94003a071e8473897fea2/artifacts
end_time: 1758705850484
entry_point_name: ''
experiment_id: '201622622176987258'
lifecycle_stage: active
run_id: c0ce679ccfb94003a071e8473897fea2
run_name: geotune-qokd9fqyuhxbgyyiuurpxu
source_name: ''
source_type: 4
source_version: ''
start_time: 1758703128167
status: 3
tags: []
user_id: '1001810000'
