# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


artifact_location: /geotunes/tune-tasks/geotune-qokd9fqyuhxbgyyiuurpxu/201622622176987258
creation_time: 1758703122737
experiment_id: '201622622176987258'
last_update_time: 1758703122737
lifecycle_stage: active
name: geotune-qokd9fqyuhxbgyyiuurpxu
