# © Copyright IBM Corporation 2025
# SPDX-License-Identifier: Apache-2.0


artifact_uri: /geotunes/tune-tasks/geotune-qokd9fqyuhxbgyyiuurpxu/201622622176987258/0fa9e4f1f90a4e6bb548f5090331a634/artifacts
end_time: 1758705851780
entry_point_name: ''
experiment_id: '201622622176987258'
lifecycle_stage: active
run_id: 0fa9e4f1f90a4e6bb548f5090331a634
run_name: top_run_geotune-qokd9fqyuhxbgyyiuurpxu
source_name: ''
source_type: 4
source_version: ''
start_time: 1758703123102
status: 3
tags: []
user_id: '1001810000'
